/*The Window Event is generated whenever we change the state of window. Closing, activating,
deactivating, opening, quiting, minimizing, maximizing a window come under this
class. Window event is generated by component such as JFrame, JInternalFrame, JDialog etc.
To handle a window event, a class must implements the WindowListener interface.
To have any component listen for a WindowEvent, we must register the component with
WindowListener as: component.addWindowListener(new MyWindowListenerO); and then
write the
public void windowOpened(WindowEvent e);
public void windowClosing(WindowEvent e);
public void window Closed(WindowEvent e);
public void windowIconified(WindowEvent e);
public void window Deiconified(WindowEvent e);
public void window Activated(WindowEvent e);
public void windowDeactivated(Window Event e); methods for the component to react to the
e v e n t .*/
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
public class WindowListenerExample extends JFrame implements WindowListener{
    JLabel label;
    public WindowListenerExample(){
        setTitle("Handling window listener");
        setSize(300,150);
        label = new JLabel("window opened");
        add(label);
        addWindowListener(this);
        setVisible(true);
    }
    public void windowOpened(WindowEvent e){
        label.setText("window opened");
    }
    public void windowClosing(WindowEvent e)
    {
        label.setText("window closing");
    }
    public void windowClosed(WindowEvent e)
    {
        label.setText("window closed");
    }
    public void windowDeiconified(WindowEvent e)
    {
        label.setText("window restored");
    }
    public void windowIconified(WindowEvent e)
    {
        label.setText("window minimized");
    }
     public void windowActivated(WindowEvent e)
    {
        label.setText("window activated");
    }
    public void windowDeactivated(WindowEvent e)
    {
        label.setText("window deactivated");
    }
    public static void main(String args[])
    {
        new WindowListenerExample();
    }


}